### ISSUE TITLE
Doesn't work when using Instant Search

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/yenWikipedia#1]
Extension doesn't work when Google Instant is turned on.

**Comment by yuvipanda** [comment]
Mostly works in trunk (for Chrome) right now. Needs a few more minor fixes before I can make a release.

**Comment by yuvipanda** [comment]
Fixed :)

**Comment by srikanthlogic** [comment]
Works for Chrome, need to port to firefox
