### ISSUE TITLE
Hijack to Wikimedia India Extension?

### ISSUE THREAD

**Issue by srikanthlogic** [yuvipanda/yenWikipedia#10]
Just a thought, Why not make it "Wikimedia India Extension" adding few more features.
1. Wiktionary thing...
2. Organise a page with recognized content (updated by script) in each language Wikipedia.
3. Pointers to Help pages in various languages
4. Links to featured portals etc

Once done, we can package it into "Wikimedia India Extension". This will definitely help Indic Wikis. More on chat

**Comment by yuvipanda** [comment]
OMG FEATURE CREEP! :P
